responsive desing
wolox-training/jd-angular pull request #10
Opened 2020-05-22 20:51 UTC by joredudiaz

## Summary

responsive design

## Jira Story

https://trello.com/c/ZVwv57W5

## Screenshot

![image](https://user-images.githubusercontent.com/44378663/82708453-ec55a880-9c43-11ea-9aee-818494ede88c.png)

2020-05-26 15:27 UTC, betoobernal commented on mock-up/scss/titles.scss
> +    display: flex;
don't repeat.

2020-05-26 15:27 UTC, betoobernal commented on mock-up/scss/tech.scss
> +    display: grid;
same

2020-05-26 15:47 UTC, betoobernal commented on mock-up/scss/styles.scss
> +    display: grid;
same

2020-05-26 19:38 UTC, betoobernal requested changes
![image](https://user-images.githubusercontent.com/4160023/82943199-d6572900-9f5e-11ea-8650-a75e4948dc06.png)

fix this when the resolution is larger than 1024

2020-05-27 12:48 UTC, FrankIglesias requested changes

2020-05-27 12:48 UTC, FrankIglesias commented on mock-up/scss/footer.scss
> +  .footer-logo {
use width and max width here

2020-05-28 15:05 UTC, betoobernal approved these changes

2020-05-28 15:36 UTC, merged