Session
wolox-training/jd-angular pull request #16
Opened 2020-05-29 21:45 UTC by joredudiaz

## Summary

- save session

## Jira Story

https://trello.com/c/RMsLYMuB

## Screenshot

![session](https://user-images.githubusercontent.com/44378663/83308101-a82a5100-a1cb-11ea-817d-b89b19bc798b.gif)

2020-05-29 22:00 UTC, FrankIglesias requested changes

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.html
> +  <a class="nav-title" (click)="closeSession()">Logout</a>
This should be a button

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.scss
> +  box-shadow: 0 0 10px 0 rgba(0,0,0,0.5);
use variables for this rgba

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.scss
> +  position: sticky;
fixed

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.scss
> +  font-family: 'roboto';
Define an equalizer to apply this font family to all texts

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.ts
> +  selector: 'app-navbar',
remove prefix from components using --no-prefix

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.ts
> +  ngOnInit(): void {
remove unnecessary functions

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.ts
> +
remove extra line

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/book-routing.module.ts
> +
remove extra line

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/book-routing.module.ts
> +      { path: 'list', component: ListComponent }
```suggestion
      { path: '', component: ListComponent }
```

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/book.component.scss
> +}
add eol here

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/book.component.scss
> +:host {
Define this as a container class attributes

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/book.component.scss
> +@import '../../../colors.scss';
remove file extension here

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/book.component.ts
> +  selector: 'app-book',
remove prefix

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/book.component.ts
> +  }
remove these

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.html
> +<div class="books"></div>
add EOL

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.html
> +<div class="books"></div>
Unnecessary div I think

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.html
> +<div class="books"></div>
Missing association with a model

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.scss
> +}
missing eol

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.scss
> +  width: 646px;
```suggestion
  max-width: 646px;
  width: 100%;
```

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.scss
> +  font-family: 'Roboto';
define this in an equalizer

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.scss
> +  padding: 32px 0 45px 0;
```suggestion
  padding: 32px 0 45px;
```

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.ts
> +
remove these

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/session.service.ts
> +    if (localStorage.length > 0) {
do you need this if?

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/app/session.service.ts
> +
remove line

2020-05-29 22:00 UTC, FrankIglesias commented on wolox-books/src/colors.scss
> +$olivine: #a0bf67;
use uppercase for colors same above

2020-05-29 22:39 UTC, joredudiaz commented on wolox-books/src/app/session.service.ts
> +    if (localStorage.length > 0) {
nup

2020-06-01 14:15 UTC, FrankIglesias requested changes

2020-06-01 14:15 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.html
> +  <button class="nav-title" (click)="closeSession()">Logout</button>
missing type here

2020-06-01 14:15 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.scss
> +  font-family: 'roboto';
remove this line

2020-06-01 14:15 UTC, FrankIglesias commented on wolox-books/src/app/screens/book/components/list/list.component.scss
> +  font-family: 'Roboto';
remove this line

2020-06-04 00:24 UTC, joredudiaz commented on wolox-books/src/app/components/navbar/navbar.component.html
> +  <button class="nav-title" (click)="closeSession()">Logout</button>
I don't understand, what type?

2020-06-05 14:25 UTC, FrankIglesias requested changes

2020-06-05 14:25 UTC, FrankIglesias commented on wolox-books/src/app/components/navbar/navbar.component.html
> +  <button class="nav-title" (click)="closeSession()">Logout</button>
```suggestion
  <button type="button" class="nav-title" (click)="closeSession()">Logout</button>
```

2020-06-16 02:26 UTC, FrankIglesias approved these changes

2020-06-16 12:05 UTC, merged