Auth
wolox-training/jd-angular pull request #17
Opened 2020-06-05 01:43 UTC by joredudiaz

## Summary

- Auth and Unauth guards

## Jira Story

https://trello.com/c/g2NDzxDO

## Screenshot

![auth](https://user-images.githubusercontent.com/44378663/83827432-f8aa1e80-a6a3-11ea-947f-d06f6f0dbce4.gif)

2020-06-05 14:20 UTC, FrankIglesias requested changes
Maybe you can join the logic of canActivate in one unique service and inside unauth and authguard call the same service

2020-06-05 14:20 UTC, FrankIglesias commented on wolox-books/src/app/auth.guard.ts
> +  }
```suggestion
    if (!this.sessionService.hasSession()) {
      this.router.navigate(['login']);
    } 
    return this.router.navigate(['login']);
  }
```

2020-06-05 19:15 UTC, betoobernal commented on wolox-books/src/app/auth.guard.ts
> +})
```suggestion
@Injectable()
```
You already are provided in a module.

2020-06-05 19:15 UTC, betoobernal commented on wolox-books/src/app/unauth.guard.ts
> +})
same

2020-06-09 23:07 UTC, joredudiaz commented
> Maybe you can join the logic of canActivate in one unique service and inside unauth and authguard call the same service

I think is better like this, because the code doesn't generate confusing, but if you like I do it

2020-06-16 02:26 UTC, FrankIglesias requested changes

2020-06-16 02:26 UTC, FrankIglesias commented on wolox-books/src/app/auth.guard.ts
> +    return true
add semi colon

2020-06-16 02:26 UTC, FrankIglesias commented on wolox-books/src/app/unauth.guard.ts
> +  canActivate(): boolean {
Move this logic to theservice

2020-06-17 14:43 UTC, betoobernal approved these changes

2020-06-18 01:33 UTC, merged