add animation to tech block
wolox-training/jd-angular pull request #6
Opened 2020-05-21 19:18 UTC by joredudiaz

## Summary

- Tech animation transition

## Jira Story

https://trello.com/c/gBCqzTik

## Screenshot

![transition](https://user-images.githubusercontent.com/44378663/82596878-b47c3180-9b6d-11ea-95de-c72ebb56ea89.gif)

2020-05-21 20:24 UTC, betoobernal commented on mock-up/scss/tech.scss
> +  transition: after 0.5s ease;
the transition is for the pseudoelement. Carry it to `&::after`

2020-05-21 20:27 UTC, betoobernal commented on mock-up/scss/tech.scss
> +  transition: after 0.5s ease;
```suggestion
  transition: right 0.5s ease, bottom 0.5s ease;
```
They are only for css properties. (not all)

2020-05-21 20:29 UTC, betoobernal commented on mock-up/scss/tech.scss
> +    left: 10px;
The transition is only for `right` and `bottom` properties.
Try this:
```suggestion
    right: -10px;
    bottom: -10px;
```
pd:
this is an exceptional case 😅

2020-05-21 21:35 UTC, FrankIglesias requested changes

2020-05-21 21:35 UTC, FrankIglesias commented on mock-up/scss/tech.scss
> +
```suggestion
&:hover::after {
    bottom: -10px;
    right: -10px;
  }
 }

```

2020-05-21 21:35 UTC, FrankIglesias commented on mock-up/scss/tech.scss
> +
Check indentation before applying this change

2020-05-22 14:53 UTC, betoobernal approved these changes

2020-05-22 15:11 UTC, merged