Navbar
wolox-training/jd-angular pull request #7
Opened 2020-05-21 20:01 UTC by joredudiaz

## Summary

- Include navbar
- Include style to navbar

## Jira Story

https://trello.com/c/VH8uBFya

## Screenshot

![navbar](https://user-images.githubusercontent.com/44378663/82600540-af21e580-9b73-11ea-80d7-5ad3a61057f0.gif)

2020-05-21 21:35 UTC, FrankIglesias requested changes

2020-05-21 21:35 UTC, FrankIglesias commented on mock-up/index.html
> +
remove extra  line

2020-05-21 21:35 UTC, FrankIglesias commented on mock-up/scss/colors.scss
> +$white: white;
```suggestion
$white: #FFF;
```

2020-05-21 21:35 UTC, FrankIglesias commented on mock-up/scss/navbar.scss
> +  position: sticky;
absolute

2020-05-22 14:44 UTC, joredudiaz commented on mock-up/scss/navbar.scss
> +  position: sticky;
if I put absolute the navbar stay in the top and when scroll the elements the whole page is scroll down (including the navbar)

2020-05-22 14:54 UTC, betoobernal commented on mock-up/index.html
> +    <img src="assets/wolox_logo.svg" alt="wolox" class="nav-logo">
add `<img/>`

2020-05-22 15:40 UTC, betoobernal approved these changes

2020-05-22 15:44 UTC, merged