Footer
wolox-training/jd-angular pull request #8
Opened 2020-05-21 21:13 UTC by joredudiaz

## Summary

- footer element
- footer style

## Jira Story

https://trello.com/c/M7HxqOFn

## Screenshot

![image](https://user-images.githubusercontent.com/44378663/82607112-d2519280-9b7d-11ea-96b7-8ce37fa66038.png)

2020-05-21 21:36 UTC, FrankIglesias requested changes

2020-05-21 21:36 UTC, FrankIglesias commented on mock-up/index.html
> +
remove extraline

2020-05-21 21:36 UTC, FrankIglesias commented on mock-up/index.html
> +  <div class="footer">
use footer tag

2020-05-21 21:36 UTC, FrankIglesias commented on mock-up/scss/footer.scss
> +.footer {
Check indentation

2020-05-21 21:36 UTC, FrankIglesias commented on mock-up/scss/tech.scss
> +  object-fit: contain;
cover instead

2020-05-21 21:50 UTC, betoobernal commented on mock-up/scss/colors.scss
>  $gray: gray;
use hexadecimal.

2020-05-21 22:05 UTC, betoobernal commented on mock-up/index.html
>        <img src="assets/rails_icon.png" alt="rails" class="tech-img">
sorry. I forget to tell you that you must close img tag. `<img />`
This allows us to treat it as if it were well-formed XML. Please fixes all

2020-05-21 22:05 UTC, betoobernal commented on mock-up/index.html
> +    <img src="assets/wolox_logo_white.svg" alt="wolox" class="footer-logo">
same

2020-05-21 22:05 UTC, betoobernal commented on mock-up/index.html
>        <img src="assets/django_icon.svg" alt="django" class="tech-img">
same

2020-05-22 14:57 UTC, betoobernal commented on mock-up/scss/footer.scss
> +  margin-right: 20px;
```suggestion
  margin: 20px 20px 0 0;
```

2020-05-22 15:41 UTC, betoobernal approved these changes

2020-05-22 15:45 UTC, merged